# metadata.db location
calibre library path: '/volume1/data/media/books/calibre'

destination root path: '/volume1/data/media/books/calibre_series'

# every books without a series will be put here
one shot folder name: '_oneshots'

# Console default to info, file default to warning. Set to change both
log level: 